[package]
name = "rust_lib_normal_chat"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"
matrix-sdk-base = { version = "0.9.0", features = ["e2e-encryption", "js"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
