[toolchain]
channel = "nightly-2025-01-05"
profile = "default"
components = ["rust-src"]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "x86_64-pc-windows-gnu",
    "wasm32-unknown-unknown",
]
